name: recikeep

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [main]
    

jobs:
  # run biome
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.7.3] 

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
        working-directory: ./
      - name: Run Biome
        run: pnpm lint
        working-directory: ./

  # run build
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.7.3] 

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
        working-directory: ./
      - name: Build with Next.js
        env: 
          NODE_ENV: development
        run: pnpm build
        working-directory: ./

