name: recikeep

on:
  push:
    branches: [main]

jobs:
  # run biome
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.7.3] 

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: pnpm install
        working-directory: ./Backend/Node/Boilerplate/
      - name: run biome
        run: pnpm lint
        working-directory: ./Backend/Node/Boilerplate/

